view/next-project/src/components/common/GlassCard.tsx, view/next-project/src/components/common/Header.tsx, view/next-project/src/pages/example.tsx
fixed #11 
GlassCardコンポーネントに渡すpropsの中にchildren，width，heightを含めた
/view/next-project/src/components/common/GlassCard.tsxのを参照してください
=> GlassCardコンポーネントの要素・スタイルを親要素から指定

view/next-project/src/components/common/GlassCard.tsx, view/next-project/src/pages/projectlist.tsx
一旦雛形はできたのでPushします。
カードのサイズはFigmaに合わせたら2つしか横に並ばなくなったので少し小さくしました。
フォントサイズも同じく小さくしました
=> [add]プロジェクト一覧ページの作成(#7)

view/next-project/src/components/common/GlassCard.tsx, view/next-project/src/components/common/TransButton.tsx, view/next-project/src/components/icons/AccountCircle.tsx, view/next-project/src/pages/projectlist.tsx
#7 
カードにホバーした際にプロジェクトの概要が表示されるようにした  
- Moreボタンを押した際の動作は非実装
- アイコンは重ねてない
- カードにホバーした時に背景色を白にするためにPropsに `background` を追加
- `TransButton.tsx` は `TestButton.tsx` をほとんど再利用した
=> [mod]プロジェクト一覧のカードへマウスホバー時に概要に切り替え(#7)

view/next-project/next.config.js, view/next-project/src/assets/base.css, view/next-project/src/components/common/FlatCard.tsx, view/next-project/src/components/common/SignIn/SignIn.module.css, view/next-project/src/components/common/SignIn/SignIn.tsx, view/next-project/src/components/common/SignIn/index.ts, view/next-project/src/components/common/SignUp/SignUp.module.css, view/next-project/src/components/common/SignUp/SignUp.tsx, view/next-project/src/components/common/SignUp/index.ts, view/next-project/src/components/common/TextButton/TextButton.module.css, view/next-project/src/components/common/TextButton/TextButton.tsx, view/next-project/src/components/common/TextButton/index.ts, view/next-project/src/pages/_app.tsx, view/next-project/src/pages/index.tsx, view/next-project/src/utils/api_methods.ts
fixed #19 
nutmeg-taro@email.com
gidaifes
でログインしてページ遷移できているか
新規登録してページ遷移できているか
=> ログイン・サインアップページの作成

api/app/controllers/api/v1/users_controller.rb, api/config/routes.rb, view/next-project/src/components/common/GlassCard.tsx, view/next-project/src/components/common/Header/Header.tsx, view/next-project/src/pages/userlist.tsx
=> メンバー一覧ページの実装

api/app/controllers/api/v1/records_api_controller.rb, api/app/models/record.rb, api/config/routes.rb, view/next-project/src/components/common/RecordDetailHeader/RecordDetailHeader.module.css, view/next-project/src/components/common/RecordDetailHeader/RecordDetailHeader.tsx, view/next-project/src/components/common/RecordDetailHeader/index.ts, view/next-project/src/pages/recordlist.tsx, view/next-project/src/pages/records/[id].tsx
レコードの詳細ページを作成したのでご確認お願いします。  
RecordDetailsHeader.tsxコンポーネントを作成し、そちらにPropsで詳細ページのヘッダーに必要な情報を渡しました。  
コンポーネント側でAPIを取得したほうがいいなら修正します。
=> レコードの詳細ページの作成

api/app/models/curriculum.rb, view/next-project/package-lock.json, view/next-project/package.json, view/next-project/src/assets/base.css, view/next-project/src/components/common/AddModal/AddModal.module.css, view/next-project/src/components/common/CurriculumAddModal.tsx, view/next-project/src/components/common/CurriculumEditModal.tsx, view/next-project/src/components/common/EditModal/EditModal.module.css, view/next-project/src/components/common/RecordAddModal.tsx, view/next-project/src/components/common/RecordEditModal.tsx, view/next-project/src/components/layout/MainLayout/MainLayout.module.css, view/next-project/src/pages/curriculums/[id].tsx, view/next-project/src/pages/records/[id].tsx
curriculumとrecordをmarkdown記法で登録できるようにしました．
今後，ボタンなどを追加していく予定です．
百々くんはある程度コードと挙動を把握しておいてもらえると助かります．
=> markdown編集・閲覧機能の追加

api/app/controllers/api/v1/skills_api_controller.rb, api/app/models/skill.rb, api/config/routes.rb, view/next-project/src/components/common/Header/Header.tsx, view/next-project/src/components/common/ListHeader/ListHeader.tsx, view/next-project/src/components/common/SkillAddModal.tsx, view/next-project/src/components/layout/MainLayout/MainLayout.module.css, view/next-project/src/pages/records/index.tsx, view/next-project/src/pages/skills/index.tsx, view/next-project/src/utils/format_date.ts
=> Skill追加機能の実装

api/app/controllers/api/v1/skills_api_controller.rb, api/config/database.yml, api/config/environments/production.rb, docker-compose.yml
- docker-compose.prod.yml
- api/config/environments/production.rb
- api/config/database.yml
- api/app/contorollers/api/v1/skills_api_contoroller.rb
=> [mod] Production環境用に整備(#75)

view/next-project/src/components/common/RecordEditModal.tsx, view/next-project/src/pages/records/[id].tsx
=> [mod]Recordの個別ページのリアクティブ化(#93)

view/next-project/src/components/common/AddModal/AddModal.tsx, view/next-project/src/components/common/CurriculumAddModal.tsx, view/next-project/src/components/common/CurriculumDeleteModal.tsx, view/next-project/src/components/common/CurriculumEditModal.tsx, view/next-project/src/components/common/DeleteModal/DeleteModal.tsx, view/next-project/src/components/common/EditModal/EditModal.tsx, view/next-project/src/components/common/ListHeader/ListHeader.tsx, view/next-project/src/components/layout/Layout/Layout.module.css, view/next-project/src/components/layout/Layout/Layout.tsx, view/next-project/src/components/layout/Layout/index.ts, view/next-project/src/components/ui/context.tsx, view/next-project/src/pages/_app.tsx, view/next-project/src/pages/curriculums/[id].tsx, view/next-project/src/pages/curriculums/index.tsx
メモ化によるパフォーマンス向上のための実装。
curriculumの追加・編集モーダルの一部を試験的にメモ化してみた。
useCallback()を使用しようと思ったが、formDataが更新された際にメモ化したコンポーネントがすべて再レンダリングされたので、一旦使わずに実装することとした。
=> [mod]curriculumの追加・編集モーダルの一部をメモ化(#91)

api/Dockerfile
=> [fix]Dockerfile(#102)

.gitignore, docker-compose.prod.yml
=> [fix]read seeds.env(#104)

docker-compose.yml
`docker compose up` 時に `server.pids` が残ってたら削除するように修正
- `docker compose up` して いつも通り動作するか
=> [fix]remove server.pids

api/Dockerfile, api/Gemfile, api/Gemfile.lock, api/config/schedule.rb, api/lib/tasks/monthly_award.rake, docker-compose.prod.yml, docker-compose.yml
ref: #136 
月末にレコード数が多い人Top３をSlackで表彰する機能の実装
- whenever の install
- cron の install
- `api/lib/tasks/monthly_award.rake` にて 定期実行の時に実行するスクリプトを記述
- 同じレコード数のユーザが複数人いた場合にも対応
- `api/config/schedule.rb` にて月末に実行する旨を記載
1. `.env.local` を `api` 以下に配置
2.  `api/config/schedule.rb` の `every '0 0 27-31 * *' do` を `every 1.minutes do` に変更する（1分おきに実行されます）。8行目のコメントアウトも外した方がいいかも？
3. `docker compose run --rm seeds_api bundle install`
4. `docker compose down -v`
5. `make rebuild`
6. `docker compose up` 
7. #notification-record_local チャンネルに通知がくるか
=>  Slack表彰機能の実装(#136)

view/next-project/src/components/common/ChapterAddModal/ChapterAddModal.tsx, view/next-project/src/components/common/CurriculumAddModal/CurriculumAddModal.tsx, view/next-project/src/components/common/CurriculumDeleteModal.tsx, view/next-project/src/components/common/CurriculumEditModal/CurriculumEditModal.tsx
チャプター入力時に contents と homework に入力した内容が反映されない問題を解決
追加で、カリキュラムの作成時に卒業課題に入力した内容が保存されない問題があったのでそれを解決
=> [fix] チャプターの追加時に入力内容が反映されない問題を解決

api/app/controllers/api/v1/users_api_controller.rb, api/app/models/user.rb, api/config/routes.rb, view/next-project/src/pages/users/index.tsx
resolve #205 
メンバー一覧ページで User と UserDetail のみを取得するようにAPI を変更
=> member一覧ページのAPIを修正

view/next-project/src/components/common/HeaderMenu/HeaderMenu.tsx, view/next-project/src/components/common/ProfileEditForm/ProfileEditForm.tsx, view/next-project/src/pages/profile/index.tsx
resolve #204
Profile画面でPC情報とtypeを編集できるようにする
RecordなどのページでAddButtonが押せない
Profile画面でPC情報とtypeを編集できるようにした
RecordなどのページでAddButtonを押せるようにした
=> [add] Profile画面でPC情報・typeを変更できるようにした (#204)

.gitignore, docker-compose.prod.yml
resolve #228 
tunnelを繋ぎ直した
gm2のcert.pemで認証し，jsonを生成した
その後，DNS設定をした
=> Seedsのデプロイ

view/next-project/src/components/common/RecordAddModal/RecordAddModal.tsx, view/next-project/src/components/common/RecordEditModal/RecordEditModal.module.css, view/next-project/src/components/common/RecordEditModal/RecordEditModal.tsx
=> 20240605 develop → main マージ #243

docker-compose.prod.yml, docker-compose.yml, view/Dockerfile
resolve #0
frontがホットリロードをするように修正
docker-compose.ymlとDockerfileを修正
volumesの指定を修正
dockerFileがなくても問題ないため削除
=> frontが開発中にホットリロードするように修正

view/next-project/src/components/common/RecordAddModal/RecordAddModal.module.css, view/next-project/src/components/common/RecordAddModal/RecordAddModal.tsx, view/next-project/src/components/common/RecordEditModal/RecordEditModal.module.css, view/next-project/src/components/common/RecordEditModal/RecordEditModal.tsx
resolve #256 
recordページの編集画面にpostページのデザインを適応した
・RecordEditModel.tsxの編集
・RecordEditModal.module.cssの編集
参考：https://chatgpt.com/share/6791c93c-fec4-800d-a27d-9b7cd66a61d8
=> recordページの編集画面にpostページのデザインを適応
